
package com.osc.cbrq.producao.pricebook;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PriceBookService", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PriceBookService {


    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.osc.cbrq.producao.pricebook.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.osc.cbrq.producao.pricebook.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param priceBookHeader
     * @return
     *     returns com.osc.cbrq.producao.pricebook.PriceBookHeader
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/createPriceBook")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "createPriceBook", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.CreatePriceBook")
    @ResponseWrapper(localName = "createPriceBookResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.CreatePriceBookResponse")
    public PriceBookHeader createPriceBook(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader)
        throws ServiceException
    ;

    /**
     * 
     * @param priceBookHeader
     * @return
     *     returns com.osc.cbrq.producao.pricebook.PriceBookHeader
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/updatePriceBook")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "updatePriceBook", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.UpdatePriceBook")
    @ResponseWrapper(localName = "updatePriceBookResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.UpdatePriceBookResponse")
    public PriceBookHeader updatePriceBook(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader)
        throws ServiceException
    ;

    /**
     * 
     * @param priceBookHeader
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/deletePriceBook")
    @RequestWrapper(localName = "deletePriceBook", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.DeletePriceBook")
    @ResponseWrapper(localName = "deletePriceBookResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.DeletePriceBookResponse")
    public void deletePriceBook(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader)
        throws ServiceException
    ;

    /**
     * 
     * @param priceBookHeader
     * @return
     *     returns com.osc.cbrq.producao.pricebook.PriceBookHeader
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/mergePriceBook")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "mergePriceBook", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.MergePriceBook")
    @ResponseWrapper(localName = "mergePriceBookResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.MergePriceBookResponse")
    public PriceBookHeader mergePriceBook(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.osc.cbrq.producao.pricebook.PriceBookHeader>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/findPriceBook")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "findPriceBook", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.FindPriceBook")
    @ResponseWrapper(localName = "findPriceBookResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.FindPriceBookResponse")
    public List<PriceBookHeader> findPriceBook(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param priceBookId
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.osc.cbrq.producao.pricebook.PriceBookHeader>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/findPriceBookById")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
    @RequestWrapper(localName = "findPriceBookById", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.FindPriceBookById")
    @ResponseWrapper(localName = "findPriceBookByIdResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.FindPriceBookByIdResponse")
    public List<PriceBookHeader> findPriceBookById(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "PriceBookId", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        long priceBookId,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param priceBookId
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/findPriceBookByIdAsync")
    @Oneway
    @RequestWrapper(localName = "findPriceBookByIdAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.FindPriceBookByIdAsync")
    public void findPriceBookByIdAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "PriceBookId", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        long priceBookId,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindControl findControl);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/findPriceBookAsync")
    @Oneway
    @RequestWrapper(localName = "findPriceBookAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.FindPriceBookAsync")
    public void findPriceBookAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        FindControl findControl);

    /**
     * 
     * @param priceBookHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/deletePriceBookAsync")
    @Oneway
    @RequestWrapper(localName = "deletePriceBookAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.DeletePriceBookAsync")
    public void deletePriceBookAsync(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader);

    /**
     * 
     * @param priceBookHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/mergePriceBookAsync")
    @Oneway
    @RequestWrapper(localName = "mergePriceBookAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.MergePriceBookAsync")
    public void mergePriceBookAsync(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader);

    /**
     * 
     * @param priceBookHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/updatePriceBookAsync")
    @Oneway
    @RequestWrapper(localName = "updatePriceBookAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.UpdatePriceBookAsync")
    public void updatePriceBookAsync(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader);

    /**
     * 
     * @param priceBookHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/createPriceBookAsync")
    @Oneway
    @RequestWrapper(localName = "createPriceBookAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.CreatePriceBookAsync")
    public void createPriceBookAsync(
        @WebParam(name = "priceBookHeader", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookHeader priceBookHeader);

    /**
     * 
     * @param priceBookItemService
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/deletePriceBookItem")
    @RequestWrapper(localName = "deletePriceBookItem", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.DeletePriceBookItem")
    @ResponseWrapper(localName = "deletePriceBookItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.DeletePriceBookItemResponse")
    public void deletePriceBookItem(
        @WebParam(name = "priceBookItemService", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookItem priceBookItemService)
        throws ServiceException
    ;

    /**
     * 
     * @param priceBookItemService
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/deletePriceBookItemAsync")
    @Oneway
    @RequestWrapper(localName = "deletePriceBookItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/", className = "com.osc.cbrq.producao.pricebook.DeletePriceBookItemAsync")
    public void deletePriceBookItemAsync(
        @WebParam(name = "priceBookItemService", targetNamespace = "http://xmlns.oracle.com/apps/orderCapture/priceBook/priceBookService/types/")
        PriceBookItem priceBookItemService);

}
